### Create numpy array 2

### numpy.arange(start,stop,step,dtype)

In [3]:
import numpy as np

In [4]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b=np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### Numpy linspace(start,stop,num,endpoint)

In [8]:
## evenly spaced samples over a secified interval

In [10]:
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [11]:
print(b[1]-b[0])

0.16326530612244916


In [12]:
print(b[2]-b[1])

0.16326530612244872


In [13]:
b=np.linspace(2,10,5)
b

array([ 2.,  4.,  6.,  8., 10.])

In [17]:
b=np.linspace(2,10,4,dtype=int)
b

array([ 2,  4,  7, 10])

In [18]:
b=np.linspace(2,10,5,dtype=int,endpoint=False)
b

array([2, 3, 5, 6, 8])

### np.identity()

In [20]:
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
b=np.eye(3,2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [25]:
b=np.identity(3,2)
b

TypeError: Cannot interpret '2' as a data type

 Diff between np.identity() and np.eye() is np identity() only get NxN but  np.eye() also get NxM

### np.random()-> gives values from 0 to 1

In [26]:
b=np.random.rand(3)
b

array([0.76505974, 0.56252981, 0.49068218])

In [29]:
b=np.random.rand(2,3)
b

array([[0.31264477, 0.59228092, 0.01059912],
       [0.96635384, 0.85206314, 0.66639328]])

## Range 0-10

In [30]:
b=np.random.rand(10)*10
b

array([7.90493767, 0.69418043, 0.48317284, 6.52153884, 9.15438034,
       8.40656357, 0.46556357, 0.32529514, 9.63172786, 2.11435331])

### np.random.randint()

In [32]:
b=np.random.randint(10,size=4)
b

array([0, 2, 1, 7])

In [33]:
np.random.randint(2, size=10)

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 1])

In [34]:
np.random.randint(5, size=(2, 4))

array([[3, 2, 3, 3],
       [0, 4, 3, 0]])

In [35]:
np.random.randint([1, 5, 7], 10)

array([1, 7, 9])