## Problem-6 : Print Elements
Problem Statement: Given a 2D integer array size (4, 5) with name input_? Print elements of highlighted matrix

In [4]:
import numpy as np



### Problem-1

In [13]:
li_2d=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr_2d=np.array(li_2d)
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [14]:
print(arr_2d[2, :3])  

[11 12 13]


### Problem-2

In [17]:
print(arr_2d[1:4,3])

[ 9 14 19]


### Problem-3

In [18]:
print(arr_2d[2:4,0:5])

[[11 12 13 14 15]
 [16 17 18 19 20]]


## Problem-4

In [20]:
print(arr_2d[1:3,1:3])

[[ 7  8]
 [12 13]]
