### Problem-12 : Height
Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm. Print the Numpy array.

In [8]:
import numpy as np
age = np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height = np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
index = np.where(height>155)
for i in range(len(index[0])) :
    print(age[index[0][i]],height[index[0][i]])


15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


### Problem-13 : Sort by column
Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
[[21 20 19 18 17]
[16 15 14 13 12]
[11 10 9 8 7]
[ 6 5 4 3 2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1



In [10]:
import numpy as np
arr = np.arange(21,1,-1)
arr = arr.reshape(4,5)
print(arr[::-1])

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
