## what will be the output on executing following code?

In [2]:
import numpy as np

In [5]:
a=np.array([0,1,2,3])
a.shape

(4,)

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.rand() #one random value

0.02633226010697176

In [8]:
np.random.randint(10,4)

ValueError: low >= high

In [9]:
#syntax for creating a random integer array ranging from 0 to 10 of size(4,4)

In [10]:
np.random.randint(10,size=(4,4))

array([[4, 4, 6, 5],
       [7, 9, 9, 4],
       [4, 4, 7, 9],
       [6, 7, 3, 1]])

## Problem Statement:
Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array

In [11]:
a=np.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

## Problem Statement:
Create an integer identity matrix of size (5, 6).
Print the Numpy array.



In [13]:
a=np.eye(5,6,dtype=int)
a

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

## Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.



In [16]:
arr = np.linspace(0,5,10)
print(arr)
for i in range(1, len(arr)-1) :
    print(round(arr[i],2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
