
## Non-zero elements

### Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements

In [3]:
import numpy as np
li=[1,2,0,0,4,0]
arr=np.array(li)
arr

array([1, 2, 0, 0, 4, 0])

In [4]:
ind=np.where(arr>0)
print(ind)

(array([0, 1, 4], dtype=int64),)


### Problem-8 : Multiples of 3
Problem Statement:
Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array array([1,3, 5, 7, 9, 11, 13, 15, 17, 19])
Print the index of elements.

In [5]:
li=[ i for i in range(1,20) if i%2==1]
li

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [6]:
arr=np.array(li)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
ind=np.where(arr%3==0)
ind

(array([1, 4, 7], dtype=int64),)

### Problem-9 : Odd elements
Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.

In [8]:
li=[i for i in range(1,11)]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
arr=np.array(li)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[arr%2==1]=-1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

## Problem-10 : Replace Max
Problem Statemnt:
Given an integer array of size 10 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])
Print the Numpy array.

In [12]:
arr=np.array([11,2,13,4,15,6,27,8,19])
arr[arr.argmax()]=0
for i in arr:
    print(i)

11
2
13
4
15
6
0
8
19


## Problem-11 : Negate Elements
Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.

In [13]:
arr=np.arange(1,11)
arr[2:8]=np.multiply(arr[2:8],-1)
for i in arr:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10
