## Boolean Indexing 2D

In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,30,(5,6))
a

array([[ 8,  9, 12, 16, 26, 14],
       [13, 18,  5,  4, 27,  6],
       [10, 28, 14, 25,  5, 29],
       [ 5, 22,  4, 27, 16,  9],
       [ 5, 23, 18, 10,  8, 23]])

In [4]:
a>20


array([[False, False, False, False,  True, False],
       [False, False, False, False,  True, False],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False, False],
       [False,  True, False, False, False,  True]])

In [5]:
bool_arr=a>20


In [6]:
ans=a[bool_arr]

In [7]:
ans

array([26, 27, 28, 25, 29, 22, 27, 23, 23])

In [8]:
b=a
print(a)

[[ 8  9 12 16 26 14]
 [13 18  5  4 27  6]
 [10 28 14 25  5 29]
 [ 5 22  4 27 16  9]
 [ 5 23 18 10  8 23]]


In [9]:
b[bool_arr]=100
print(b)

[[  8   9  12  16 100  14]
 [ 13  18   5   4 100   6]
 [ 10 100  14 100   5 100]
 [  5 100   4 100  16   9]
 [  5 100  18  10   8 100]]


In [12]:
c=np.random.randint(1,10,(2,2))

In [13]:
c

array([[3, 6],
       [8, 7]])

In [15]:
c_bool=np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [16]:
print(c[c_bool])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [19]:
print(b)

[[  8   9  12  16 100  14]
 [ 13  18   5   4 100   6]
 [ 10 100  14 100   5 100]
 [  5 100   4 100  16   9]
 [  5 100  18  10   8 100]]


In [20]:
bool_arr=b[:,3]==100
print(bool_arr)

[False False  True  True False]


In [21]:
b[bool_arr,3]==99
print(b)

[[  8   9  12  16 100  14]
 [ 13  18   5   4 100   6]
 [ 10 100  14 100   5 100]
 [  5 100   4 100  16   9]
 [  5 100  18  10   8 100]]
