## Boolean Indexing

In [1]:
import numpy as np
a=np.array(['t','b','r','d','e','f','z','a'])
b=np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 9  1  7 13 14 16  2  5]


In [2]:
bool_arr=b>10
print(bool_arr)

[False False False  True  True  True False False]


In [3]:
new_arr=b[bool_arr]
new_arr

array([13, 14, 16])

In [4]:
new_arr=b[b>10]
print(new_arr)

[13 14 16]


In [5]:
new_arr=b[(b>10) & (b<18)]
new_arr

array([13, 14, 16])

In [6]:
print(b)

[ 9  1  7 13 14 16  2  5]


In [7]:
c=b
c

array([ 9,  1,  7, 13, 14, 16,  2,  5])

In [8]:
c[:3]=19

In [9]:
c

array([19, 19, 19, 13, 14, 16,  2,  5])

In [10]:
c[c>15]=100

In [11]:
c

array([100, 100, 100,  13,  14, 100,   2,   5])

In [13]:
np.where(b[b==100])

(array([0, 1, 2, 3], dtype=int64),)

In [14]:
ind=np.where(b[b==100])

In [15]:
print(ind)

(array([0, 1, 2, 3], dtype=int64),)


In [16]:
print(a[ind])

['t' 'b' 'r' 'd']
