### create a numpy array

In [1]:
import numpy as np
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


### Numpy array containts homogeneous elements

In [2]:
a=[1,2,3,4,'5']
b=np.array(a,dtype=int)
print(b)


[1 2 3 4 5]


In [3]:
a=[1,2,3,'5',4.5]
b=np.array(a*3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


### Numpy functions

## ones()

In [6]:
b=np.ones(3)
b

array([1., 1., 1.])

In [8]:
b=np.ones(3,dtype=int)  # by default data type f numpy array is float
b

array([1, 1, 1])

In [10]:
b=np.zeros(3,dtype=int)
b

array([0, 0, 0])

## creating 2D array

In [11]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

## Zeros()

In [13]:
b=np.zeros(3,dtype=int)
b

array([0, 0, 0])

In [12]:
b=np.zeros((3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Full()

In [15]:
b=np.full(3,5.)
b

array([5., 5., 5.])

In [16]:
b=np.full((3,3),5,dtype=str)
b

array([['5', '5', '5'],
       ['5', '5', '5'],
       ['5', '5', '5']], dtype='<U1')

## empty()

In [17]:
### This function returns the uninitialized data that have shape dtype and order defined in function

In [22]:
x=np.empty(3)
x

array([5., 5., 5.])

## What will be the output

In [21]:
a=np.empty(4,dtype=int)
print(a)
## integer array of size 4 with all numbers of integers

[-1142590481 -1703420619  -164814277  -320205894]


## Assignment-1

In [24]:
#Given 2D list create a numpy 2D array using it. 2D list is [[1,2,3],[4,5,6],[7,8,9]]

In [25]:
li=[[1,2,3],[4,5,6],[7,8,9]]
ans=np.array(li)
ans

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Assignment-2

# Problem Statement:
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1. Print the elements of array.

In [33]:
a=np.zeros(10,dtype=int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])