## indexing and slicing

In [1]:
import numpy as np

In [3]:
li=[1,2,3,4]
arr=np.array(li)
print(li)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [4]:
print(arr.data)

In [5]:
print(arr.shape)

(4,)


In [6]:
print(arr.dtype)

int32


In [8]:
print(arr.strides) ## from one element to another element 4 byte

(4,)


In [12]:
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)
print(li_2d)
print(arr_2d)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
print(arr_2d.data)

In [14]:
print(arr_2d.shape)

(4, 4)


In [15]:
print(arr_2d.dtype)

int32


In [18]:
print(arr_2d.strides) ## one row  to one row we have to 16 bit skip and one element to another element we hace to do 4 byte skip 

(16, 4)


### slicing

In [19]:
print(li[3])

4


In [20]:
print(arr[3])

4


In [21]:
print(li[1:4])

[2, 3, 4]


In [22]:
print(arr[1:4])

[2 3 4]


## 2D array slicing

In [23]:
print(li_2d[2][1])

10


In [24]:
print(arr_2d[2][1])

10


In [25]:
print(arr_2d[2][1])

10


In [26]:
print(arr_2d[2,1])

10


In [27]:
print(li_2d[1][0:3])

[5, 6, 7]


In [28]:
print(arr_2d[1, :3])

[5 6 7]


In [29]:
print(li_2d[0:3][3])

IndexError: list index out of range

In [30]:
x=li_2d[0:3]

In [31]:
print(x)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [32]:
y=x[2]
print(y)

[9, 10, 11, 12]


In [33]:
print(arr_2d[0:3,2])

[ 3  7 11]


In [34]:
print(li_2d[0:3][3])

IndexError: list index out of range

In [35]:
print(li_2d[0:3][0])

[1, 2, 3, 4]


In [36]:
print(arr_2d[2:4,1:3])

[[10 11]
 [14 15]]


In [37]:
print(li_2d[2:4][1:3])

[[13, 14, 15, 16]]


In [38]:
print(li_2d[2:4][1:3])

[[13, 14, 15, 16]]


## what will be the o/p

In [39]:
a=np.array([0,1,2,3])

In [40]:
a.shape

(4,)