In [1]:
import numpy as np

In [2]:
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 7 15 12 14  4]
[11 12 13  2 15]


In [3]:
li=[i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [5]:
a=a+1
a

array([ 9, 17, 14, 16,  6])

In [6]:
c=a+b
c

array([20, 29, 27, 18, 21])

In [7]:
d=a-b
d

array([-2,  5,  1, 14, -9])

In [8]:
e=a*b
e

array([ 99, 204, 182,  32,  90])

In [9]:
f=a/b
f

array([0.81818182, 1.41666667, 1.07692308, 8.        , 0.4       ])

In [10]:
g=a//b
g

array([0, 1, 1, 8, 0], dtype=int32)

In [12]:
h=a**b  #a^b
h

array([1316288537, 1333592769,  521986048,        256, 2033549312],
      dtype=int32)

In [13]:
print(a.sum())

62


In [14]:
print(a.mean())

12.4


In [15]:
print(a.min())

6


In [16]:
print(a.argmin())

4


In [17]:
print(a.max())

17


In [18]:
print(a.argmax())

1


In [19]:
print(a)
print(b)

[ 9 17 14 16  6]
[11 12 13  2 15]


In [20]:
a>b

array([False,  True,  True,  True, False])

In [21]:
a==b

array([False, False, False, False, False])

In [22]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [23]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [24]:
print(np.logical_not(a))

[False False False False False]


In [25]:
a[2]=0
print(a)

[ 9 17  0 16  6]


In [26]:
print(np.logical_not(a))

[False False  True False False]
